- name: Create node_exporter user
  user:
    name: node_exporter
    shell: /sbin/nologin

- name: Download Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: Extract Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy binary
  copy:
    src: /tmp/node_exporter-1.8.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: 0755

- name: Create systemd service
  copy:
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=default.target
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644

- name: Start and enable node_exporter
  systemd:
    name: node_exporter
    enabled: yes
    state: started
    daemon_reload: yes

